version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "12345:8545"

networks:
  default:
    name: polygon-network-v2
    external: true


