version: '3.8'

services:
  redis_db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: redis_db
    command: redis-server
    volumes:
      - ./redis-data:/data

  postgres:
    image: postgres:14
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data

  blockscout:
    depends_on:
      - postgres
      - redis_db
      #- smart-contract-verifier
    image: blockscout/blockscout:latest
    pull_policy: always
    #restart: always
    #stop_grace_period: 5m
    container_name: 'blockscout'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      -  ./envs/common-blockscout.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
        
        JSON_RPC: http://nginx:8545/
        ETHEREUM_JSONRPC_HTTP_URL: http://nginx:8545/
        ETHEREUM_JSONRPC_TRACE_URL: http://nginx:8545/
        CHAIN_ID: '85000'
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/blockscout?ssl=false
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
        API_V2_ENABLED: 'false'
        MIX_ENV: 'prod'

        TRACE_FIRST_BLOCK: 1
        FIRST_BLOCK: 1

        INDEXER_CATCHUP_BLOCKS_CONCURRENCY: 2
        INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY: 2
        INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: 2
        INDEXER_RECEIPTS_BATCH_SIZE: 2
        INDEXER_COIN_BALANCES_BATCH_SIZE: 2
        INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE: 2

        POOL_SIZE: 90
        POOL_SIZE_API: 50

        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: 'false'
        INDEXER_DISABLE_BLOCK_REWARD_FETCHER: 'true'
        INDEXER_DISABLE_CATALOGED_TOKEN_UPDATER_FETCHER: 'false'

        #BLOCK_TRANSFORMER: clique
        # ETHEREUM_JSONRPC_VARIANT: 'nethermind'
        ETHEREUM_JSONRPC_VARIANT: geth

        INDEXER_MEMORY_LIMIT: '10Gb'
     
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/

  # smart-contract-verifier:
  #   extends:
  #     file: ./services/docker-compose-smart-contract-verifier.yml
  #     service: smart-contract-verifier

  # visualizer:
  #   extends:
  #     file: ./services/docker-compose-visualizer.yml
  #     service: visualizer

  # sig-provider:
  #   extends:
  #     file: ./services/docker-compose-sig-provider.yml
  #     service: sig-provider
networks:
  default:
    name: polygon-network-v2
    external: true

